dist: trusty
language: python
python:
 - "3.5"
install:
 - pip install pytest pytest-cov pytest-pep8
 - pip install coveralls
 - pip install -r requirements.txt
 - python3.5 -m nltk.downloader punkt # Install the data needed by NLTK to tokenize
script:
 - py.test
after_success:
 - coveralls